# Generated by Django 6.0 on 2025-12-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institution_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('institution_name', models.CharField(max_length=191)),
                ('password', models.CharField(max_length=191)),
                ('abbreviation', models.CharField(default='COLLEGE', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('student', 'Student'), ('class_head', 'Class Head'), ('subject_head', 'Subject Head'), ('parent', 'Parent')], max_length=20)),
            ],
        ),
    ]
