# Generated by Django 6.0 on 2026-01-03 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=191)),
                ('subject_head', models.CharField(max_length=191)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=191)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classes')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
