# Generated by Django 6.0 on 2026-01-06 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_subjects"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassNameMapping",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "class_name_keywords",
                    models.TextField(
                        help_text="Comma-separated keywords for this class type"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        help_text="Abbreviation for this class type", max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        help_text="Class this mapping belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.classes",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this mapping belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.institution",
                    ),
                ),
            ],
        ),
    ]
