# Generated by Django 6.0 on 2026-01-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_classnamemapping"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classnamemapping",
            name="class_obj",
        ),
    ]
